language: php

php:
 - 5.3
 - 5.4

env: MYSQL='{"dsn":"mysql:dbname=kohana","username":"root"}' POSTGRESQL='{"dsn":"pgsql:dbname=kohana"}' SQLITE='{"dsn":"sqlite:kohana.sqlite3"}'

before_script:
 - mysql -e 'CREATE DATABASE kohana'
 - psql -c 'CREATE DATABASE kohana'
