language: php

php:
 - 5.3
 - 5.4

env: MYSQL='{"dsn":"mysql:dbname=kohana","username":"root"}' POSTGRESQL='{"dsn":"pgsql:dbname=kohana"}' SQLITE='{"dsn":"sqlite:kohana.sqlite3"}'

before_script:
 - pear config-set auto_discover 1
 - pear install --nodeps pear.phpunit.de/DbUnit
 - mysql -e 'CREATE DATABASE kohana'
 - mysql -B kohana < tests/integration/SQL/MySQL/schema.sql
 - createdb kohana
 - psql -n kohana < tests/integration/SQL/PostgreSQL/schema.sql
 - sqlite3 kohana.sqlite3 < tests/integration/SQL/SQLite/schema.sql

script: "composer validate && phpunit"
