language: php

php:
 - 5.3
 - 5.4

env:
  global:
    - MYSQL='{"dsn":"mysql:dbname=kohana","username":"root"}'
    - POSTGRESQL='{"dsn":"pgsql:dbname=kohana"}'
    - SQLITE='{"dsn":"sqlite:kohana.sqlite3"}'
  matrix:
    - COMPOSER=
    - COMPOSER=composer.json

before_install:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo 2> /dev/null | mysql -B mysql
  - sudo apt-get --no-install-recommends -qq install language-pack-fr && sudo locale-gen fr_FR
  - test -z "$COMPOSER" || composer install --dev
  - test -n "$COMPOSER" || pear config-set auto_discover 1
  - test -n "$COMPOSER" || pear install --nodeps pear.phpunit.de/DbUnit

before_script:
 - mysql -e 'CREATE DATABASE kohana'
 - mysql -B kohana < tests/integration/SQL/MySQL/schema.sql
 - createdb kohana
 - psql -n kohana < tests/integration/SQL/PostgreSQL/schema.sql
 - sqlite3 kohana.sqlite3 < tests/integration/SQL/SQLite/schema.sql

script: >
  composer validate &&
  if [ "$COMPOSER" ] ; then
    vendor/bin/phpunit --bootstrap vendor/autoload.php
  else
    phpunit
  fi
