language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - MYSQL='{"dsn":"mysql:dbname=kohana","username":"root"}'
    - MYSQL_NATIVE='{"database":"kohana","username":"root"}'
    - POSTGRESQL='{"dsn":"pgsql:dbname=kohana"}'
    - POSTGRESQL_NATIVE='{"database":"kohana"}'
    - SQLITE='{"dsn":"sqlite:kohana.sqlite3"}'
  matrix:
    - COMPOSER=composer.json
    - ERROR_REPORTING=0
    - ERROR_REPORTING=-1

before_install:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo 2> /dev/null | mysql -B mysql
  - sudo apt-get --no-install-recommends -qq install language-pack-fr && sudo locale-gen fr_FR
  - test -z "$COMPOSER" || composer install --dev
  - test -n "$COMPOSER" || pyrus set auto_discover 1
  - test -n "$COMPOSER" || pyrus install phpunit/DbUnit

before_script:
 - mysql -e 'CREATE DATABASE kohana'
 - mysql -B kohana < tests/integration/SQL/MySQL/schema.sql
 - createdb kohana
 - psql -n kohana < tests/integration/SQL/PostgreSQL/schema.sql
 - sqlite3 kohana.sqlite3 < tests/integration/SQL/SQLite/schema.sql

script: >
  composer validate &&
  if [ "$COMPOSER" ] ; then
    vendor/bin/phpunit -d error_reporting=$ERROR_REPORTING --bootstrap vendor/autoload.php
  else
    phpunit -d error_reporting=$ERROR_REPORTING
  fi
